import { redirect } from 'next/navigation'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ReduxProvider from "./ReduxProvider";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import Link from 'next/link';
import AuthProvider from './context/AuthProvider';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

 
  return (
    <html lang="en">

      <body className={inter.className}>
     <AuthProvider>

       <ReduxProvider>
       <Header />
         {children}
       </ReduxProvider>
     </AuthProvider>
  
        </body>
    </html>
  );
}
